# Default configuration for running experiments

# TRAIN STEPS
MAX_TRAIN_STEPS = 5000

# minibatch settings
BATCH_SIZE_TR_LOADER = 256
BATCH_SIZE_TR_LOADER_EVAL = 2048
BATCH_SIZE_VAL_LOADER = 2048
BATCH_SIZE_TEST_LOADER = 2048

